spring:
  application:
    name: CinemaManager
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_CONNECTION_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.yml
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

omdb-api:
  url: ${OMDB_API_URL:http://www.omdbapi.com/}
  key: ${OMDB_API_KEY}

